---
  - name: Get instances info
    hosts: localhost
    gather_facts: no

    tasks:

      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
        register: ec2_instance_info

      - name: Printing the public dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].public_dns_name }}"