---
  - name: Update etc hosts 
    hosts: localhost
    gather_facts: no

    tasks:
    
      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
          filters:
            instance-state-name: [ "running"]
        register: ec2_instance_info

      - name: Print the private ip address
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_ip_address }}"

      - name: Setting the private_ip variable
        ansible.builtin.set_fact:
          private_ip: "{{ ec2_instance_info.instances[0].private_ip_address }}"
      
      - name: Print the private dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_dns_name }}"
      
      - name: Setting the private_name variable
        ansible.builtin.set_fact:
          private_name: "{{ ec2_instance_info.instances[0].private_dns_name }}"

      - name: Copy the index.html for the website
        ansible.builtin.template:
          src: etc.hosts.j2
          dest: /etc/hosts
          owner: root
          group: root
          mode: u+rw,g-wx,o-wx