---
  - name: Update etc hosts 
    hosts: localhost
    gather_facts: no

    tasks:
    
      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
          filters:
            instance-state-name: [ "running"]
        register: ec2_instance_info

      - name: Get the private ip address
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_ip_address }}"
      
      - name: Get the private dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_dns_name }}"