---
  - name: Get instances info
    hosts: localhost
    connection: local
    gather_facts: no
  
    tasks:

      - name: Get instances id with tag {{name}} in {{region}}
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
        register: ec2_node_info

      - name: foobar
        ansible.builtin.debug:
          msg: "{{ec2_node_info.instances.network_interfaces.association.public_dns_name}}"
