---
  - name: Get instances info
    hosts: localhost
    gather_facts: no

    tasks:
    
      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
        register: ec2_instance_info

      - name: Printing the public dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].public_dns_name }}"

      - name: Send an email with the link to the aap demo Server
        community.general.mail:
          host: "{{ smtpserver }}"
          port: "{{ smtp_port }}"
          secure: try
          username: "{{ username }}"
          password: "{{ password }}"
          subject: Ansible Automation Platform (AAP) Daily Demo
          body: "This server was just built using AAP. The playbooks and notes can be found here: https://github.com/redawg/Ansiblewesttigers/tree/master/Demonstrations/AAP_daily_demo  The server will be destroyed at 01:00 AM UTC time. This URL will take you to the webserver: http://{{ ec2_instance_info.instances[0].public_dns_name }} You can admin the machine here: https://{{ ec2_instance_info.instances[0].public_dns_name }}:9090 or use ssh command to login: ssh ec2-user@{{ ec2_instance_info.instances[0].public_dns_name }}"
          from: "{{ mailfrom }}"
          to: "{{ mailto }}"
          bcc: "{{ bccto }}"