---
  - name: Get instances info
    hosts: localhost
    gather_facts: no

    tasks:

      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
        register: ec2_instance_info

      - name: Printing the public dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].public_dns_name }}"

      - name: Send an email with the link to the aap demo Server
        community.general.mail:
          host: "{{ smtpserver }}"
          port: "{{ smtp_port }}"
          secure: try
          username: "{{ username }}"
          password: "{{ password }}"
          subject: AAP Daily Demo
          body: "This server was just built and will be up until 6 pm PHX time.  http://{{ ec2_instance_info.instances[0].public_dns_name }}"
          from: "{{ mailfrom }}"
          to: "{{ mailto }}"