---
  - name: Get private ip and dns name
    hosts: localhost
    gather_facts: no

    tasks:
    
      - name: "Get instances in {{region}}"
        amazon.aws.ec2_instance_info:
          region: "{{region}}"
          filters:
            instance-state-name: [ "running"]
        register: ec2_instance_info

      - name: Print the private ip address
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_ip_address }}"

      - name: Setting the private_ip variable
        ansible.builtin.set_stats:
          data:
            private_ip: "{{ ec2_instance_info.instances[0].private_ip_address }}"
      
      - name: Print the private dns name
        ansible.builtin.debug:
          msg:  "{{ ec2_instance_info.instances[0].private_dns_name }}"
      
      - name: Setting the private_name variable
        ansible.builtin.set_stats:
          data:
            private_name: "{{ ec2_instance_info.instances[0].private_dns_name }}"