---
  - name: Get instances info
    hosts: localhost
    connection: local
    gather_facts: yes
    vars:
       aws_access_key: ''
       aws_secret_key: ''
       region: ''
       name: ''

    tasks:

     - name: Get instances id with tag {{name}} in {{region}}
       amazon.aws.ec2_instance_info:
        region: "{{region}}"
    
     - name:
       ansible.builtin.debug:
          msg: 
          - "http://{{ ansible_facts['public_dns_name'] }}"