---
  - name: Get instances info
    hosts: localhost
    gather_facts: no

    tasks:

    - name: "Get instances id with tag {{servername}} in {{region}}"
      amazon.aws.ec2_instance_info:
        region: "{{region}}"
        filters:
          "tag:name": "{{servername}}"
      register: foobar

    - name: Printing the public dns name
      ansible.builtin.debug:
        msg:  "{{foobar}}"