---
- name: example from docs.ansible.com for AWS module
  hosts: localhost
  
  tasks:
  
  - name: Gather information about all customer gateways
    ec2_customer_gateway_info:
      region: us-west-1
    register: cust_gw_info
    
  - name: Output cust_gw_info
    debug:
      var: cust_gw_info
