---
  - name: Gather AWS instance info
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''

    tasks:

    - name: Get instances id with tag {{ servername }} in {{ region }}
      register: instance_info
      amazon.aws.ec2_instance_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ servername }}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{ my_email_address }}"
      
    - name: Printing out instance_info.instances[0].instance_id
      when: instance_info.instances[0].instance_id is defined
      ansible.builtin.debug:
         msg: "{{ instance_info.instances[0].instance_id }}"

    - name: Printing the public dns name
      ansible.builtin.debug:
        msg:  "{{ instance_info.instances[0].public_dns_name }}"

    - name: Capture public dns name
      ansible.builtin.set_stats:
        data:
          my_server: "{{ instance_info.instances[0].public_dns_name }}"