---
  - name: Testing the URI module to login to AAP
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

      - name: Login to a form based webpage, then use the returned cookie to access the app in later tasks
        ansible.builtin.uri:
          url: "https://{{ tower_url }}/api/v2/tokens"
          method: POST
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
          force_basic_auth: yes
          status_code: 301
          return_content: yes       
        register: token

      - name: AWS Inventory Sync
        ansible.builtin.uri:
          url: https://{{ tower_url }}/api/v2/inventory_sources/72/update/
          method: POST
          return_content: yes
          headers:
            Cookie: "{{ token.cookies_string }}"