---
  - name: Testing the URI module to login to AAP
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

      - name: Login to a form based webpage, then use the returned cookie to access the app in later tasks
        ansible.builtin.uri:
          url: "https://{{ tower_url }}/api/v2/tokens/"
          method: POST
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
          force_basic_auth: yes
          status_code: 201
          return_content: yes       
        register: new_token

      - name: Debug token
        debug: 
          msg: "{{ new_token.json.token }}"

      - name: AWS Inventory Sync
        ansible.builtin.uri:
          url: "https://{{ tower_url }}/api/v2/inventory_sources/72/update/"
          headers:
            Authorization: "Bearer {{ new_token.json.token }}"
            Content-Type: "application/json"
          validate_certs: no
          follow_redirects: all
          return_content: yes
          method: "POST"
        register: output

      - name: Print output
        debug:
          msg: "{{ output }}"